### ISSUE TITLE
CAT PICTURE SQUISHED 😾

### ISSUE THREAD

**Issue by jxu** [aftix/hblog#1]
my UI

**Comment by aftix** [comment]
Can you please describe your issue

**Comment by jxu** [comment]
Between 600 and 800 px width, hero.css height is 19rem which causes image aspect ratio to change. Actually the image is already squashed by default.
Below 600 px width, the height is fixed at 26 rem with the same issue.
I'm actually not sure how this should be handled on mobile. Site headers are usually not images.

**Comment by jxu** [comment]
🐈‍⬛
